// Canonical catalog for services appearing on the landing page
// This is used for one-off seeding/upserts in admin flows.

import { SERVICE_TYPES } from "../utils/constants.js";

export const servicesCatalog = [
  // {
  //   name: "AI Astrologer Chat",
  //   slug: "ai-chat",
  //   description: "Conversational guidance with curated AI astrologer personalities available 24x7.",
  //   serviceType: SERVICE_TYPES.AI_CHAT,
  //   basePrice: 0,
  //   isPaid: false,
  //   features: ["Instant Sanskritised remedies", "Multiple personas", "Chat history saved"],
  //   metadata: { href: "/chat", accent: "bg-[color:var(--color-secondary)]/10" },
  //   isActive: true
  // },
  {
    name: "Kundli / Birth Chart",
    slug: "kundli",
    description:
      "Precise Janam Kundli with grah-bal, varshphal and remedy recommendations.",
    serviceType: SERVICE_TYPES.KUNDLI,
    basePrice: 799,
    isPaid: true,
    features: ["AI narrative", "PDF download", "Strength & remedies"],
    metadata: { accent: "bg-[color:var(--color-primary)]/10" },
    isActive: true,
  },
  {
    name: "Kundli Matching",
    slug: "matching",
    description: "Guna Milan, dosha analysis and विवाह अनुकूलता सुझाव.",
    serviceType: SERVICE_TYPES.KUNDLI_MATCHING,
    basePrice: 999,
    isPaid: true,
    features: ["36 guna score", "Compatibility band", "Remedy checklist"],
    metadata: { accent: "bg-[color:var(--color-accent)]/10" },
    isActive: true,
  },
  {
    name: "Daily Panchang",
    slug: "panchang",
    description:
      "Sunrise, tithi, yoga, and shubh muhurat personalised to your city.",
    serviceType: SERVICE_TYPES.PANCHANG,
    basePrice: 0,
    isPaid: false,
    features: ["Custom location", "Festival alerts", "Auspicious times"],
    metadata: { accent: "bg-[color:var(--color-secondary)]/10" },
    isActive: true,
  },
  {
    name: "Daily Horoscope",
    slug: "horoscope",
    description:
      "AI-crafted भविष्यफल with Hindi + English summaries across key areas.",
    serviceType: SERVICE_TYPES.HOROSCOPE_DAILY,
    basePrice: 0,
    isPaid: false,
    features: ["Love/Finance/Health", "Mood mantra", "Shareable cards"],
    metadata: { accent: "bg-[color:var(--color-primary)]/10" },
    isActive: true,
  },
  {
    name: "Lal Kitab Horoscope",
    slug: "lal-kitab",
    description:
      "Classical Lal Kitab rules and गृह-फल insights tailored for your chart.",
    serviceType: SERVICE_TYPES.HOROSCOPE_LAL_KITAB,
    basePrice: 499,
    isPaid: true,
    features: ["Upay calendar", "Grah remedies", "House wise tips"],
    metadata: { accent: "bg-[color:var(--color-accent)]/10" },
    isActive: true,
  },
  {
    name: "Gochar Phal",
    slug: "gochar-phal",
    description:
      "Transit-based prediction for major ग्रह गोचर and retrograde periods.",
    serviceType: SERVICE_TYPES.HOROSCOPE_GOCHAR,
    basePrice: 299,
    isPaid: true,
    features: ["Transit timeline", "Risk alerts", "Monthly focus"],
    metadata: { accent: "bg-[color:var(--color-secondary)]/10" },
    isActive: true,
  },
  {
    name: "Career Counselling",
    slug: "career-counselling",
    description: "Identify favourable योग, दशाएं और growth periods.",
    serviceType: SERVICE_TYPES.CAREER,
    basePrice: 699,
    isPaid: true,
    features: ["Decision matrix", "Skill mantra", "Opportunity calendar"],
    metadata: { accent: "bg-[color:var(--color-primary)]/10" },
    isActive: true,
  },
  {
    name: "Life Report",
    slug: "life-report",
    description:
      "Comprehensive जीवन रिपोर्ट covering health, धन, परिवार, और करियर.",
    serviceType: SERVICE_TYPES.LIFE_REPORT,
    basePrice: 1199,
    isPaid: true,
    features: ["10-year outlook", "Quarterly focus", "Remedy stack"],
    metadata: { accent: "bg-[color:var(--color-accent)]/10" },
    isActive: true,
  },
  {
    name: "Year Analysis",
    slug: "year-analysis",
    description: "Varshphal breakdown with प्रमुख प्राथमिकताएँ और शुभ समय.",
    serviceType: SERVICE_TYPES.YEAR_ANALYSIS,
    basePrice: 899,
    isPaid: true,
    features: ["Month-by-month", "Priority score", "Festival guidance"],
    metadata: { accent: "bg-[color:var(--color-secondary)]/10" },
    isActive: true,
  },
  {
    name: "Baby Name Suggestion",
    slug: "baby-name",
    description: "Nakshatra, राशि और अर्थ-संगत सुन्दर नाम सुझाव.",
    serviceType: SERVICE_TYPES.BABY_NAME,
    basePrice: 299,
    isPaid: true,
    features: ["Multiple themes", "Meaning guide", "Lucky syllables"],
    metadata: { accent: "bg-[color:var(--color-primary)]/10" },
    isActive: true,
  },
  {
    name: "Mangal Dosha Check",
    slug: "mangal-dosha",
    description: "Manglik प्रभाव का सरल विश्लेषण और उपाय सुझाव.",
    serviceType: SERVICE_TYPES.MANGAL_DOSHA,
    basePrice: 199,
    isPaid: true,
    features: ["Impact score", "Parihar steps", "Temple guide"],
    metadata: { accent: "bg-[color:var(--color-accent)]/10" },
    isActive: true,
  },
  {
    name: "Kal Sarp Dosh Analysis",
    slug: "kal-sarp-dosh",
    description: "दोष की प्रकार, प्रभाव और उपायों का सार.",
    serviceType: SERVICE_TYPES.KAL_SARP_DOSH,
    basePrice: 249,
    isPaid: true,
    features: ["Dosha type", "Ritual check", "Gemstone pairing"],
    metadata: { accent: "bg-[color:var(--color-secondary)]/10" },
    isActive: true,
  },
  // {
  //   name: "Gemstone Store",
  //   slug: "gemstone",
  //   description:
  //     "Lab-certified रत्न, energisation, और डिलीवरी tracking in-app.",
  //   serviceType: SERVICE_TYPES.GEMSTONE,
  //   basePrice: 0,
  //   isPaid: false,
  //   features: ["Certified gems", "Energisation guide", "Wallet checkout"],
  //   metadata: { href: "/store", accent: "bg-[color:var(--color-primary)]/10" },
  //   isActive: true,
  // },
];
